FORMAT: 1A

# Quiz

Quiz Api auf Basis von PHP RedBean, um Datenbankzugriffe zu ermöglichen

## Erklärungen

Requests: 

- Header: Der Header beinhaltet Informationen für die Ausführung der Abfrage
- Body: Der Body enthält Daten, welche eingetragen werden sollen
- session Token (token): Der Token wird mitgegeben, wenn für die Ausführung der Aktion eine Anmeldung erforderlich ist. Aktuell angemeldete Nutzer sind in der sessions Tabelle hinterlegt

Responses:

- Response Code 200: Bedeutet, dass die Aktion erfolgreich durchgeführt worden ist und beinhaltet ggf. das Ergebnis der Abfrage
- Response Code 400: Bedeutet, dass bei der Aktion ein Fehler aufgetreten ist

# Group Quiz 

***DB Tabelle Quiz***<br>
Anforderungen an die/ Funktion der Quiz Schnittstelle

## Quiz Anfragen [/quiz.php]
### Liste der Quizze [GET]

+ Request

	+ Headers 
			
			action: list

+ Response 200 (application/json)

		{
		    "1": {
		        "id": "1",
		        "name": "Quiz 1",
		        "description": "Quiz 1 Beschreibung",
		        "user_iduser": "1",
		        "category_idcategory": "1"
		    },
		    "2": {
		        "id": "2",
		        "name": "Quiz 2",
		        "description": "Quiz 2 Beschreibung",
		        "user_iduser": "1",
		        "category_idcategory": "1"
		    }
		}

### Quiz Eintrag anfordern [GET]

+ Request

	+ Headers

			action: entry
			id: 1

+ Response 200 (application/json)
		
		{
			"id": 1,
			"name": "Name des Quiz",
			"description": "Beschreibung des Quiz",
			"user": "Nutzername des Ersteller",
			"user_id": 12,
			"user_description" : "Beschreibung des	Nutzers aus dem Profil",
			"category" : "Kategorie des Quiz (String)"
		}

### Quiz vollständig anfordern [GET]

+ Request
	
	+ Headers

			action: fullQuiz
			id: 1

+ Response 200 (application/json)
		
		{
			"id": 7,
			"name":"Quiz name 2", 
			"description": "Beschreibung des Quiz",
			"user" : "Nutzername des Ersteller",
			"user_description" : "Beschreibung des	Nutzers aus dem Profil",
			"category" : "Kategorie des Quiz (String)",
			"questions":
				[
					{
						"text": "Der Inhalt der Frage",
						"answers":
							[
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": true
								}
							]
					},
					{
						"text": "Der Inhalt der Frage",
						"answers":
							[
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": true
								}
							]
					},
					{
						"text": "Der Inhalt der Frage",
						"answers":
							[
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": false
								},
								{
									"text": "Der Inhalt einer Antwortmöglichkeit",
									"isCorrect": true
								}
							]
					}
				]
		}

### Quiz hinzufügen [POST]

+ Request

	+ Headers
			
			action: addQuiz
			token: sessionToken

	+ Body

			{
			  "name": "Name des Quiz",
			  "description": "Beschreibung des Quiz",
			  "user_iduser": 1,
			  "category_idcategory": 1
			}

+ Response 200 (application/json)
		
		{
			"status": "ok",
			"quiz_id": 12
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Quiz aktualisieren (ändern) [PUT]

+ Request

	+ Headers

			action: updateQuiz
			id: 12
			token: sessionToken

	+ Body
			
			{
				"name": "Name des Quiz",
				"description": "Beschreibung des Quiz",
				"user_id": 12,
				"category" : "Kategorie des Quiz (Id)"
			}

+ Response 200 (application/json)
		
		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Quiz entfernen [DELETE]

Ein Quiz darf nur dann entfernt werden, wenn keine Fragen anhängen. Oder alle Fragen und dazugehörigen Antworten mitgelöscht werden.

+ Request
	
	+ Headers

			action: deleteQuiz
			id: 12
			token: sessionToken

+ Response 200 (application/json)

		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

# Group Frage

***DB Tabelle Question***<br>
Alle Fragebezogenen Anfragen sind in dieser Gruppe

## Fragen Anfragen [/question.php]
### Liste der zu einem Quiz zugehörigen Fragen [GET]

+ Request

	+ Header

			action: getQuestion
			quiz_id: 15

+ Response 200 (application/json)

		[
			{
				"id": 133,
				"text": "Inhalt der Frage",
				"quiz_id": 15
			},
			{
				"id": 134,
				"text": "Inhalt der Frage",
				"quiz_id": 15
			},
			{
				"id": 135,
				"text": "Inhalt der Frage",
				"quiz_id": 15
			},
			{
				"id": 136,
				"text": "Inhalt der Frage",
				"quiz_id": 15
			}
		] 

### Einzelne Frage anfordern [GET]

+ Request

	+ Header

			action: getSingleQuestion
			id: 17

+ Response 200 (application/json)

		{
			"id": 17,
			"text": "Inhalt der Frage",
			"quiz_id": 15
		}

### Frage erstellen [POST]

+ Request
	
	+ Header

			action: addQuestion
			token: sessionToken

	+ Body

			{
				"text": "Inhalt der Frage",
				"quiz_id": 15
			}

+ Response 200 (application/json)

		{
			"status":"ok",
			"question_id": 178
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Frage ändern [PUT]

+ Request
	
	+ Header

			action: updateQuestion
			id: 198
			token: sessionToken

	+ Body

			{
				"text": "Inhalt der Frage",
				"quiz_id": 15
			}

+ Response 200 (application/json)
		
		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Frage löschen [DELETE]

Eine Frage darf nur dann gelöscht werden, wenn keine Antworten anhängend sind.

+ Request
	
	+ Header

			action: deleteQuestion
			id: 166
			token: sessionToken

+ Response 200 (application/json)

		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

# Group Antwort

***DB Tabelle: Answer***<br>
Fasst Schnittstelle für Antworten zusammen

## Antworten Anfragen [/answer.php]
### Liste von Antworten nach Frage ID [GET]

+ Request
	
	+ Header

			action: getAnswer
			question_id: 12

+ Response 200 (application/json)
		
		[
			{
			"id": 146,
			"text": "Der Inhalt des Antwort Text",
			"question_id": 12,
			"isCorrect": false
			},
			{
			"id": 147,
			"text": "Der Inhalt des Antwort Text",
			"question_id": 12,
			"isCorrect": false
			},
			{
			"id": 148,
			"text": "Der Inhalt des Antwort Text",
			"question_id": 12,
			"isCorrect": true
			},
			{
			"id": 149,
			"text": "Der Inhalt des Antwort Text",
			"question_id": 12,
			"isCorrect": false
			}
		]

### Einzelne Antwort nach ID [GET]

+ Request

	+ Header

			action: getSingleAnswer
			id: 146

+ Response 200 (application/json)
		
		{
			"id": 146,
			"text": "Der Inhalt des Antwort Text",
			"question_id": 12,
			"isCorrect": false
		}

### Antwort erstellen [POST]

+ Request

	+ Header

			action: createAnswer
			token: sessionToken

	+ Body

			{
				"text": "Der Inhalt der Antwort",
				"question_id": 7,
				"isCorrect": true
			}

+ Response 200 (application/json)
		
		{
			"status": "ok",
			"answer_id": 546
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}
		
### Antwort anpassen [PUT]

+ Request
	
	+ Header

			action: updateAnswer
			id: 148
			token: sessionToken

	+ Body

			{
				"text": "Der Inhalt der Antwort",
				"question_id": 9,
				"isCorrect": true
			}

+ Response 200 (application/json)
		
		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Antwort löschen [DELETE]

+ Request
	
	+ Header

			action: deleteAnswer
			id: 144
			token: sessionToken

+ Response 200 (application/json)
		
		{
			"status":"ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

# Group Nutzer

***DB Tabelle user***<br>
Nutzerbezogene Aktionen werden damit durchgeführt

## Nutzer Anfragen [/user.php]
### Nutzer by ID [GET]

+ Request
	
	+ Header

			action: getUserByID
			id: 45

+ Response 200 (application/json)
		
		{
			"id": 45,
			"username": "Nutzername",
			"description": "Beschreibung des Nutzers"
		}

### Nutzer LOGIN [GET]

+ Request

	+ Header

			action: getLogin
			uname: username
			pwd: encryptedPWD

+ Response 200 (application/json)
		
		{
			"status": "ok",
			"token" : "asdfghjiebweiselvs"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Get User by Name [GET]

+ Request
	
	+ Header

			action: getUserByName
			name: Nutzername

+ Response 200 (application/json)
		
		{
			"id": 45,
			"username": "Nutzername",
			"description": "Beschreibung des Nutzers"
		}

### Nutzer erstellen [POST]

+ Request

	+ Header

			action: createUser

	+ Body

			{
				"username": "Nutzername",
				"pwd": "encryptedPasswordHash",
				"description": "Beschreibung des Nutzers"
			}

+ Response 200 (application/json)
		
		{
			"status":"ok",
			"id": 188
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Nutzer ändern [PUT]

Für Änderungen beim Nutzer muss stets das Passwort neu eingetippt werden.

+ Request
	
	+ Header

			action: updateUser
			id: 12
			pwd: encryptedHash
			token: sessionToken

	+ Body

			{
				"pwd": "encryptedPasswordHash",
				"description": "Beschreibung des Nutzers"
			}

+ Response 200 (application/json)

		{
			"status": "ok"
		}

### Nutzer löschen [DELETE]

Ein Nutzer darf nur dann gelöscht werden, wenn er kein Quiz mehr besitzt.

+ Request
	
	+ Header

			action: deleteUser
			id: 145
			pwd: encryptedHash
			token: sessionToken

+ Response 200 (application/json)
		
		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

# Group Kategorie

***DB Tabelle category***<br>
Kategorienbezogene Anfragen befinden sich hier

## Anfragen Kategorien [/category.php]
### Liste der Kategorien [GET]

+ Request
		
	+ Header
	
			action: getAllCategories

+ Response 200 (application/json)

		{
			"1":{
				"id": 27,
				"name": "name der Kategorie"
			},
			"3":{
				"id": 28,
				"name": "name der Kategorie"
			},
			"2":{
				"id": 29,
				"name": "name der Kategorie"
			}
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Einzelne Kategorie by ID [GET]

+ Request 
	
	+ Header

			action: getCategory
			id: 27

+ Response 200 (application/json)
		
		{
			"id": 27,
			"name": "name der Kategorie"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Kategorie anlegen [POST]

+ Request
	
	+ Header

			action: addCategory
			token: sessionToken

	+ Body

			{
				"name": "Name der neuen Kategorie"
			}

+ Response 200 (application/json)
		
		{
			"status": "ok",
			"id": 297
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Kategorie ändern [PUT]

+ Request
		
	+ Header

			action: updateCategory
			id: 15
			token: sessionToken

	+ Body

			{
				"name": "neuer Name"
			}

+ Response 200 (application/json)
		
		{
			"status": "ok"
		}

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

### Kategorie löschen [DELETE]

Entfernt die Kategorie. Soll nur dann gehen, wenn die Kategorie nicht benutzt wird.<br>

+ Request
		
	+ Header

			action: deleteCategory
			id: 146
			token: sessionToken

+ Response 200 (application/json)
		
		{
			"status": "ok"
		} 

+ Response 400 (application/json)
		
		{
			"status": "failed"
		}

# Group Sessions
## Anfragen zu Nutzersessions [/sessions.php]
### Ausloggen aus der aktuellen Session [DELETE]

Beendet die aktuelle Session und entfernt den Token aus der Datenbank

+ Request
	
	+ Header

			action: endSession
			token: sessionToken

+ Response 200 (application/json)
		
		{
			"status":"ok"
		}